apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: oppfolgingsplanarbeidsgiver
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: "docker.pkg.github.com/navikt/oppfolgingsplanarbeidsgiver:{{tag}}"
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 60
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://tjenester.nav.no/oppfolgingsplanarbeidsgiver"
    - "https://oppfolgingsplanarbeidsgiver.nais.oera.local"
  env:
    - name: APPRES_CMS_URL
      value: https://appres.nav.no
    - name: LOGINSERVICE_URL
      value: https://loginservice.nav.no/login
    - name: SYFOAPI_SYFOTEKSTERAPI_URL
      value: https://syfoapi.nais.oera.no/syfotekster/api/tekster
    - name: SYKEFRAVAERAPI_URL
      value: https://itjenester.oera.no/syforest
    - name: OPPFOELGINGSDIALOGAPI_URL
      value: https://restoppfoelgingsdialog.nais.oera.no/restoppfoelgingsdialog/api
