apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: oppfolgingsplanarbeidsgiver
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://tjenester.nav.no/oppfolgingsplanarbeidsgiver"
    - "https://oppfolgingsplanarbeidsgiver.nais.oera.no"
  env:
    - name: DECORATOR_URL
      value: "https://nav.no/dekoratoren"
    - name: LOGINSERVICE_URL
      value: https://loginservice.nav.no/login
    - name: SYKEFRAVAERAPI_URL
      value: https://itjenester.oera.no/syforest
    - name: SYFOOPRESTAPI_URL
      value: https://syfooprest.nais.oera.no/syfooprest/api
