export const HENTER_SYKMELDT = 'HENTER_SYKMELDT';
export const SYKMELDT_HENTET = 'SYKMELDT_HENTET';
export const HENT_SYKMELDT_FEILET = 'HENT_SYKMELDT_FEILET';
export const HENT_SYKMELDT_FORESPURT = 'HENT_SYKMELDT_FORESPURT';
