export const HENTER_SYKMELDTE = 'HENTER_SYKMELDTE';
export const SYKMELDTE_HENTET = 'SYKMELDTE_HENTET';
export const HENT_SYKMELDTE_FEILET = 'HENT_SYKMELDTE_FEILET';
export const HENT_SYKMELDTE_FORESPURT = 'HENT_SYKMELDTE_FORESPURT';
export const HENT_SYKMELDTE_BERIKELSER_FORESPURT = 'HENT_SYKMELDTE_BERIKELSER_FORESPURT';
export const HENTER_SYKMELDTE_BERIKELSER = 'HENTER_SYKMELDTE_BERIKELSER';
export const HENT_SYKMELDTE_BERIKELSER_FEILET = 'HENT_SYKMELDTE_BERIKELSER_FEILET';
export const SYKMELDTE_BERIKELSER_HENTET = 'SYKMELDTE_BERIKELSER_HENTET';

export const HENTER_SYKMELDINGER = 'HENTER_SYKMELDINGER';
export const SYKMELDINGER_HENTET = 'SYKMELDINGER_HENTET';
export const HENT_SYKMELDINGER_FEILET = 'HENT_SYKMELDINGER_FEILET';
export const HENT_SYKMELDINGER_FORESPURT = 'HENT_SYKMELDINGER_FORESPURT';
